# Generated by Django 4.1.7 on 2023-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
