# Generated by Django 4.1.7 on 2023-05-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="Title",
            new_name="title",
        ),
    ]
