# Generated by Django 4.1.7 on 2023-07-01 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("dr_name", models.CharField(max_length=30)),
                ("prescription", models.ImageField(upload_to="documents/image/")),
                ("report", models.FileField(upload_to="documents/pdfs/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
