# Generated by Django 4.1.7 on 2023-05-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_title_blog_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="Likes",
            new_name="likes",
        ),
    ]
